apiVersion: apps/v1
kind: Deployment
metadata:
  name: basicphpapp
spec:
  selector:
    matchLabels:
      app: basicphpapp
  template:
    metadata:
      labels:
        app: basicphpapp
    spec:
      containers:
      - name: basicphpapp
        image: praveen13/basicphpapp
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"



---

apiVersion: v1
kind: Service
metadata:
  name: basicphpappservice
spec:
  type: NodePort
  selector:
    app: basicphpapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30009

