apiVersion: v1
kind: Pod
metadata:
  name: usesecret
spec:
  containers:
  - name: busybox
    image: busybox
    command: ["bin/sh"]
    args: ["-c","sleep 300"]
    env:
    - name: myname
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
