apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    learn: kube
    fun: learn
spec:
  replicas: 3
  selector:
    matchLabels:
      learn: kube
  template:
    metadata:
      labels:
        learn: kube
    spec:
      containers:
      - name: mypodname
        image: praveen13/basicphpapp

